### ISSUE TITLE
Worker container config should use environment variables for DB

### ISSUE THREAD

**Issue by jessecureton** [ciur/papermerge#114]
The [app production config](https://github.com/ciur/papermerge/blob/master/docker/1.4/config/app.production.py) uses environment variables for `POSTGRES_HOST`/`POSTGRES_USER`/etc. The [worker production config](https://github.com/ciur/papermerge/blob/master/docker/1.4/config/worker.production.py) uses static definitions for the DB connection.

The environment variables are very useful for running in container orchestration frameworks like Kubernetes or Nomad, and it would be great to not have to patch the worker container's production config at runtime.

Can the default worker config be updated to match the default app config & use the env variables?

**Comment by ciur** [comment]
@jessecureton, sure ! It can :) 
To be honest, I rarely use docker. But if you do this change, I will gladly accept your pull request! :grin:

**Comment by jessecureton** [comment]
Opened a PR against stable/1.4.x in #115. Let me know if there's anything you'd prefer to change :)

**Comment by ciur** [comment]
@jessecureton I merged your pull request. Thank you!
Just now, after merge was complete, I thought that maybe your PR was work in progress... :)
It it was work in progress, please, next time mark it with [WIP] prefix (work in progress).

Thank you for your contribution!

**Comment by ciur** [comment]
@jessecureton, I am little bit confused. Is this ticket good to close ?

**Comment by ciur** [comment]
@jessecureton, you changes were added to master and 1.4.x branches.
1.4.3 release will be available next week (somewhere between 14-18 Sept 2020) so that you would test if the changes did the trick for you.
I rely on you, guys, to test docker part. As I mentioned above I don't use docker myself :)

**Comment by cbirkenbeul** [comment]
I just cloned your repo and like to install papermerge on docker by myself. The Worker itself seems to read the wrong variables, because I still get the issue on the log:
`psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known`
Maybe there is more to fix than the one config file?

**Comment by jessecureton** [comment]
Hi @ciur! Yes, I did a local build of the container with my changes and pushed it to a local docker repo. All seemed to work as expected. I will upgrade my deployment to 1.4.3 when it is available and report if there are any issues.

**Comment by ciur** [comment]
great! thank you!
